name: build_website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Run build script
        run: python main.py
      - name: auth
        run: git config --global user.email "oreoignter@gmail.com"
      - name: auth
        run: git config --global user.name "thisisignitedoreo"
      - name: stage changed files
        run: git add index.html
      - name: commit changed files
        run: git commit -m "[WEBSITE] Auto-rebuild"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
