name: build_website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run build script
        run: python main.py
      - name: stage changed files
        run: git add index.html
      - name: commit changed files
        run: git commit -m "[WEBSITE] Auto-rebuild"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
